name: playground
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - arviz
  - binutils-meta
  - bokeh
  - bqplot
  - c-compiler
  - cartopy
  - cmocean
  - compilers
  - cudatoolkit=10.2
  - cupy
  - cxx-compiler
  - cython
  - dask
  - dask-jobqueue
  - dask-labextension
  - distributed
  - fortran-compiler
  - gcsfs
  - graphviz
  - hvplot
  - intake
  - intake-esm
  - intake-xarray
  - ipycanvas
  - ipyevents
  - ipyleaflet=0.12.6
  - ipympl
  - ipysheet
  - ipytree
  - ipyvolume=0.6.0a6
  - ipyvuetify
  - ipywidgets
  - jax
  - jaxlib
  - jupyterlab
  - jupyterlab-nvdashboard
  - line_profiler
  - matplotlib
  - libnetcdf=4.7.4=*_105
  - nodejs
  - numba
  - pip
  - proplot
  - pyjanitor
  - pymc3
  - pysnooper
  - python-graphviz
  - python=3.7
  - pythreejs
  - pytorch
  - pywwt
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - sidecar
  - datashader
  - tqdm
  - voila-vuetify
  - voila=0.1
  - xarray
  - zarr
  - cmip6_preprocessing
  - geoviews
  - spatialpandas
