#!/bin/bash

jupyter labextension install \
                            @jupyter-widgets/jupyterlab-manager \
                            dask-labextension jupyterlab-nvdashboard \
                            @jupyter-widgets/jupyterlab-sidecar bqplot \
                            jupyter-threejs jupyter-leaflet ipysheet \
                            ipytree ipycanvas jupyter-matplotlib jupyter-vuetify ipyvolume \
                            @jupyter-voila/jupyterlab-preview @pyviz/jupyterlab_pyviz \
                            @krassowski/jupyterlab-lsp @mamba-org/gator-lab


#EOF
