name: playground
channels:
  - conda-forge
  - pytorch
  - fastai
  - defaults
dependencies:
  # - libnetcdf=4.7.4=*_105
  - arviz
  - binutils-meta
  - bokeh
  - bqplot
  - c-compiler
  - cartopy
  - cmip6_preprocessing
  - cmocean
  - compilers
  - cudatoolkit=10.2
  - cupy
  - cxx-compiler 
  - cython
  - dask
  - dask-jobqueue
  - dask-labextension
  - datashader
  - distributed
  - fastai
  - fortran-compiler
  - gcsfs
  - geemap
  - geoviews
  - geoviews
  - graphviz
  - hvplot
  - intake
  - intake-esm
  - intake-xarray
  - ipycanvas
  - ipyevents
  - ipyleaflet=0.12.6
  - ipympl
  - ipysheet
  - ipytree
  - ipyvolume=0.6.0a6
  - ipyvuetify
  - ipywidgets
  - jax
  - jaxlib
  - jupyterlab
  - jupyterlab-nvdashboard
  - libopencv 
  - line_profiler
  - matplotlib
  - nodejs
  - numba
  - opencv 
  - panel
  - pip
  - proplot
  - py-opencv
  - pyjanitor
  - pymc3
  - pysnooper
  - python-graphviz
  - python=3.7
  - pythreejs
  - pytorch
  - pyvista
  - pywwt
  - redis
  - redis-py
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - sidecar
  - spacy
  - spatialpandas
  - spatialpandas
  - tensorboard
  - torchvision
  - tqdm
  - voila-vuetify
  - voila=0.1
  - vtk
  - xarray
  - xesmf
  - xrft
  - zarr
  - pip:
      - sktime
      - handcalcs
      - git+https://github.com/holoviz/hvplot.git@interactive_api
      - git+https://github.com/intake/intake-esm.git
