name: playground
channels:
  - conda-forge
  - pytorch
  - fastai
  - defaults
dependencies:
  # - libnetcdf=4.7.4=*_105
  - arviz
  - binutils-meta
  - bokeh>=2.2.3
  - bqplot
  - c-compiler
  - cartopy
  - cmip6_preprocessing
  - cmocean
  - compilers
  - cudatoolkit=10.2
  - cupy>=8.1.0
  - cxx-compiler
  - cython
  - dask-jobqueue
  - dask-labextension
  - dask>=2.30
  - datashader
  - distributed>=2.30
  - fastai
  - fortran-compiler
  - gcsfs
  - geemap
  - geoviews
  - graphviz
  - hvplot
  - intake
  - intake-esm>=2020.11.4
  - intake-xarray
  - ipycanvas
  - ipyevents
  - ipyleaflet>=0.12.6
  - ipympl
  - ipysheet
  - ipytree
  - ipyvolume>=0.6.0a6
  - ipyvuetify
  - ipywidgets
  - jax
  - jaxlib
  - jupyter-lsp
  - jupyterlab
  - jupyterlab-nvdashboard
  - kaggle
  - libopencv
  - line_profiler
  - matplotlib
  - nc-time-axis
  - nodejs
  - numba>=0.51.2
  - numpyro
  - opencv
  - panel
  - pip
  - proplot
  - py-opencv
  - pyjanitor
  - pymc3>=3.9
  - pysnooper
  - python-graphviz
  - python-language-server
  - python=3.8
  - pythreejs
  - pytorch>=1.7.0
  - pyvista
  - pywwt
  - redis
  - redis-py
  - regionmask
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - sidecar
  - spacy
  - spatialpandas
  - tensorboard
  - torchvision
  - tqdm
  - voila-vuetify
  - voila>=0.1
  - vtk
  - xarray>=0.16
  - xesmf>=0.4
  - xrft
  - zarr>=2.5
  - pip:
      - handcalcs
      - scalene
      - sktime
